### ISSUE TITLE
Implement embedded RGB smart contract validation procedures

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rust-lnpbp#115]
Before introduction of simplicity some specific complex forms of validation (like zk-validation for confidential amounts ensuring that the sum of inputs is always equal to the sum of outputs) is made with embedded rust procedures, which are the part of this library. However, to cover all initial schemata functionality we need to implement more (this is an incomplete list):
* Fungible assets
  - [x] Primary issuance
  - [x] Asset transfer
  - [ ] Secondary issuance
  - [ ] Burn verification for asset burning
  - [ ] Replacement (re-issuance after burn)
  - [ ] On-chain bitcoin lock verification (for decentralized issuance)
* Non-fungible assets
  - [ ] Primary issuance
  - [ ] Asset transfer
  ...
* Reputation
  ...
* Audit logs
  ...
