### ISSUE TITLE
[blocking] Rebase on new rust-bitcoin library versions

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rust-lnpbp#127]
Pending release of rust-bitcoin crates:
- [ ] bitcoin_hashes https://github.com/rust-bitcoin/bitcoin_hashes/pull/96: removes need in maintaining our own fork
- [ ] rust-bitcoin https://github.com/rust-bitcoin/rust-bitcoin/pull/491: removes need in all non-PSBT additions to the crate

so we can stop maintaining fork after we ...
- [ ] separate all PSBT functionality into separate crate https://github.com/LNP-BP/rust-psbt
- [ ] remove support of custom forks from bitcoin crates, including rust-miniscript (needed only because of underlying bitcoin fork dependency)
