### ISSUE TITLE
[EPIC]: Add Tor support throughout all protocols

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rust-lnpbp#23]
This will involve modification of rust-bitcoin and rust-lightning libraries and related PRs to them

Upstream PRs:
- [ ] https://github.com/teawithsand/torut/pull/7
- [ ] https://github.com/teawithsand/torut/pull/6
- [ ] https://github.com/teawithsand/torut/pull/5

**Comment by dr-orlovsky** [comment]
Closing since too generic and not related to this repo anymore
