### ISSUE TITLE
Make upstream PRs accepted & publish v0.1.0 release on crates.io

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rust-lnpbp#77]
## TODOs
- [ ] Make all PRs in upstream crates merged
- [ ] Get version bump in upstream crates after the last PR released
- [ ] Complete code docs https://github.com/LNP-BP/rust-lnpbp/issues/81
- [ ] Remove all dead code https://github.com/LNP-BP/rust-lnpbp/blob/6010402f8e49fd05ad23f8c0e93ffe079d33d378/src/lib.rs#L33
- [ ] Remove re-exporting of bitcoin crates https://github.com/LNP-BP/rust-lnpbp/blob/6010402f8e49fd05ad23f8c0e93ffe079d33d378/src/lib.rs#L64

## Upstream dependencies requiring attention
- [x] grin_secp256k1zkp
- [x] bitcoin_hashes
- [ ] rust-bitcoin
- [x] rust-lightning
- [ ] miniscript

## List of opened upstream PRs
- [ ] All PSBT and BIP-32-related PRs from epic https://github.com/rust-bitcoin/rust-bitcoin/issues/473
- [ ] (optional) All bitcoin_num related PRs from epic https://github.com/rust-bitcoin/rust-bitcoin/issues/467
- [ ] Taproot-related PRs
- [x] https://github.com/rust-bitcoin/bitcoin_hashes/pull/90
- [ ] https://github.com/rust-bitcoin/bitcoin_hashes/pull/89
- [x] https://github.com/rust-bitcoin/rust-miniscript/pull/70
- [x] https://github.com/rust-bitcoin/rust-bitcoin/pull/388
- [x] https://github.com/rust-bitcoin/rust-bitcoin/pull/480
- [x] https://github.com/rust-bitcoin/rust-bitcoin/pull/435
- [x] https://github.com/rust-bitcoin/rust-lightning/pull/623
- [x] https://github.com/rust-bitcoin/rust-bitcoin/pull/395
- [x] https://github.com/rust-bitcoin/rust-bitcoin/pull/387
...
