### ISSUE TITLE
Replace grin_secp256k1zkp with secp256k1-zkp for bulletproofs & Pedersen commitments

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rust-lnpbp#78]
Using https://github.com/ElementsProject/secp256k1-zkp/pull/23

- [ ] get it merged
- [ ] do rust bindings
- [ ] get new version released to crates.io
