### ISSUE TITLE
Complete LNP (lightning networking protocol) implementation

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rust-lnpbp#79]
- [x] Internet2 networking with TCP & ZMQ
- [x] Feature management
- [x] Noise encryption
- [x] LN-specific data types (only `BigInt` left)
- [x] Messages: BOLT-1
- [x] Messages: BOLT-2
- [ ] Messages: BOLT-7
- [x] LN-specific data types encoding
